; CHIPI ESP32-Audio v3.0
; PlatformIO Configuration

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Librerías
lib_deps =
    gilmaimon/ArduinoWebsockets@^0.5.4

; Flags de compilación
build_flags =
    -D BOARD_HAS_PSRAM=0
    -D CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=3

; Partición con OTA
board_build.partitions = min_spiffs.csv

; Monitor filters
monitor_filters = esp32_exception_decoder, default

; OTA Upload (descomentar para usar)
upload_protocol = espota
upload_port = chipi-esp32-test.local
upload_flags = --auth=
